# Generated by Django 4.1.2 on 2022-10-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alunos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="genero",
            field=models.CharField(default="x", max_length=1),
        ),
    ]
